Issue #1746 - Revert "Update NSPR to 4.29"
This reverts commit 149d2ffa779826cb48a381099858e76e4624d471.

diff --git a/nsprpub/pr/tests/Makefile.in b/nsprpub/pr/tests/Makefile.in
--- a/nsprpub/pr/tests/Makefile.in
+++ b/nsprpub/pr/tests/Makefile.in
@@ -211,7 +211,6 @@ ifdef NS_USE_GCC
 else
   EXTRA_LIBS += ws2_32.lib
   LDOPTS = -NOLOGO -DEBUG -DEBUGTYPE:CV -INCREMENTAL:NO
-  CFLAGS += -Fd$(@:.$(OBJ_SUFFIX)=.pdb)
   ifdef PROFILE
     LDOPTS += -PROFILE -MAP
   endif # profile
@@ -443,4 +442,17 @@ endif
 ALWAYS:
 
 runtests:: $(PROGS) ALWAYS
-	$(topsrcdir)/pr/tests/runtests.sh $(DIST)
+	@$(ECHO) "\nNSPR Test Results - $(OBJDIR)\n"
+	@$(ECHO) "BEGIN\t\t\t`date`"
+	@$(ECHO) "NSPR_TEST_LOGFILE\t$(LOGFILE)\n"
+	@$(ECHO) "Test\t\t\tResult\n"
+	@cd $(OBJDIR); for i in $(PROGRAMS); do					\
+	$(ECHO) "$$i\c";										\
+	./$$i >> $(LOGFILE) 2>&1 ;								\
+	if  [ 0 = $$? ] ; then									\
+		$(ECHO) "\t\t\tPassed";								\
+	else													\
+		$(ECHO) "\t\t\tFAILED";								\
+	fi;														\
+	done
+	@$(ECHO) "\nEND\t\t`date`\n"
